### ISSUE TITLE
experimental ThresholdedRelu

### ISSUE THREAD

**Issue by LuisHsu** [ONNC/onnc-runtime#139]

**Comment by LuisHsu** [comment]
No function content

**Comment by akioolin** [comment]
sorry for forgot. re-send code again.

**Comment by LuisHsu** [comment]
No function content again.
Maybe you just `git commit` to your localhost and forgot to `git push` it.

**Comment by akioolin** [comment]
the following git commands sequence is used to put code into github.

git checkout -b $1
git add src/lib/operator/$1.c
git status
git commit
git remote -v
git status
git push origin $1

do I miss some thing?

Is it possible to delete thresholdedrelu branch?


2018-07-27 11:37 GMT+08:00 徐朝逸 <notifications@github.com>:
